name: Heritage Photography
favicon: null
layout_spectrum: 0.0708
typography_spectrum: 0.65155
title: Follow the journey of a sprouting photographer.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5197dc'
    - '#090a05'
    - '#ccd5de'
    - '#465327'
    - '#7c8a35'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
