title: Follow the journey of a sprouting photographer.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#171312'
    - '#960C1B'
    - '#5B0C14'
    - '#985440'
    - '#C58A6C'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Heritage Photography
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.65155
layout_spectrum: 1
